source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'pg'
gem 'puma'
gem 'activerecord'
gem 'rack-cors', require: 'rack/cors'
gem "rackup", "~> 2.1"
gem 'rubyzip'
gem 'rack'
gem 'fastimage'